name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build C sources
      run: |
        for file in c/*.c; do
          if [[ "$file" == *_incomplete.c ]]; then
            continue
          fi
          gcc -std=c11 "$file" -lm -o "/tmp/$(basename "${file%.c}")"
        done
    - name: Build C++ sources
      run: |
        for file in cpp/*.cpp; do
          g++ -std=c++17 "$file" -o "/tmp/$(basename "${file%.cpp}")"
        done
